// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WebAppRazorpage.ApiModel;
//
//    var apiRoleModel = ApiRoleModel.FromJson(jsonString);

namespace WebAppRazorpage.ApiModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ApiRoleModel
    {
        [JsonProperty("roleName")]
        public string RoleName { get; set; }

        [JsonProperty("accounts")]
        public object Accounts { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("createdTime")]
        public DateTimeOffset CreatedTime { get; set; }

        [JsonProperty("lastUpdated")]
        public DateTimeOffset LastUpdated { get; set; }

        [JsonProperty("deleteTime")]
        public object DeleteTime { get; set; }
    }

    public partial class ApiRoleModel
    {
        public static List<ApiRoleModel> FromJson(string json) => JsonConvert.DeserializeObject<List<ApiRoleModel>>(json, WebAppRazorpage.ApiModel.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<ApiRoleModel> self) => JsonConvert.SerializeObject(self, WebAppRazorpage.ApiModel.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
