// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WebAppRazorpage.ApiModel;
//
//    var auctionEvent = AuctionEvent.FromJson(jsonString);

namespace WebAppRazorpage.ApiModel
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using WebAppRazorpage.ApiModel.Base;

    public partial class AuctionEventModel
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("createdTime")]
        public DateTimeOffset CreatedTime { get; set; }

        [JsonProperty("lastUpdated")]
        public DateTimeOffset LastUpdated { get; set; }

        [JsonProperty("deleteTime")]
        public DateTimeOffset? DeleteTime { get; set; }

        [JsonProperty("beginDateTime")]
        public DateTimeOffset BeginDateTime { get; set; }

        [JsonProperty("endDateTime")]
        public DateTimeOffset EndDateTime { get; set; }

        [JsonProperty("auctionStatus")]
        public string AuctionStatus { get; set; }

        [JsonProperty("staffId")]
        public string StaffId { get; set; }

        [JsonProperty("account")]
        public AccountModel Account { get; set; }

        [JsonProperty("auctionStates")]
        public List<AuctionStateModel> AuctionStates { get; set; }
    }

    public partial class AuctionEventModel
    {
        public static List<AuctionEventModel> FromJson(string json) => JsonConvert.DeserializeObject<List<AuctionEventModel>>(json, Converter.Settings);
    }


}
