// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WebAppRazorpage.ApiModel;
//
//    var apiRoleModel = ApiRoleModel.FromJson(jsonString);

namespace WebAppRazorpage.ApiModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using WebAppRazorpage.ApiModel.Base;

    public partial class RoleModel
    {
        [JsonProperty("roleName")]
        public string RoleName { get; set; }

        [JsonProperty("accounts")]
        public object Accounts { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("createdTime")]
        public DateTimeOffset CreatedTime { get; set; }

        [JsonProperty("lastUpdated")]
        public DateTimeOffset LastUpdated { get; set; }

        [JsonProperty("deleteTime")]
        public object DeleteTime { get; set; }
    }

    public partial class RoleModel
    {
        public static List<RoleModel> FromJson(string json) => JsonConvert.DeserializeObject<List<RoleModel>>(json, Converter.Settings);
    }

}
